version: '3.8'


services:
  backend:
    image: sahariardev/chat-backend:latest
    ports:
      - "8080:8080"

  auth:
    image: sahariardev/auth:latest
    ports:
      - "5000:5000"

  frontend:
    image: sahariardev/chat-backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
